### ISSUE TITLE
04d_storing_data_in_ultra-fast_hdf5.ipynb

### ISSUE THREAD

**Issue by sandpalmtree** [PacktPublishing/Algorithmic-Trading-with-Python-Cookbook#2]
**Describe the bug**
spy_equity = obb.equity.price.historical(
    ticker, start_date="2021-01-01", provider="yfinance"
)

**Expected behavior**
Get data.

**Response I keep getting**

---------------------------------------------------------------------------
OpenBBError                               Traceback (most recent call last)
Cell In[46], line 1
----> 1 spy_equity = obb.equity.price.historical(
      2     ticker, start_date="2021-01-01", provider="yfinance"
      3 )

File [~\anaconda3\envs\my-quant-stack\lib\site-packages\openbb_core\app\static\utils\decorators.py:89](http://localhost:8889/lab/workspaces/auto-V/tree/ATPC/Algorithmic-Trading-with-Python-Cookbook/04.%20Store%20Financial%20Market%20Data%20on%20Your%20Computer/~/anaconda3/envs/my-quant-stack/lib/site-packages/openbb_core/app/static/utils/decorators.py#line=88), in exception_handler.<locals>.wrapper(*f_args, **f_kwargs)
     85     raise OpenBBError(f"\n[Error] -> {error_str}").with_traceback(
     86         tb
     87     ) from None
     88 if isinstance(e, OpenBBError):
---> 89     raise OpenBBError(f"\n[Error] -> {str(e)}").with_traceback(tb) from None
     90 raise OpenBBError("\n[Error] -> Unexpected error.").with_traceback(
     91     tb
     92 ) from None

File [~\anaconda3\envs\my-quant-stack\lib\site-packages\openbb_yfinance\models\equity_historical.py:165](http://localhost:8889/lab/workspaces/auto-V/tree/ATPC/Algorithmic-Trading-with-Python-Cookbook/04.%20Store%20Financial%20Market%20Data%20on%20Your%20Computer/~/anaconda3/envs/my-quant-stack/lib/site-packages/openbb_yfinance/models/equity_historical.py#line=164), in YFinanceEquityHistoricalFetcher.extract_data(query, credentials, **kwargs)
    146 data = yf_download(
    147     symbol=query.symbol,
    148     start_date=query.start_date,
   (...)
    161     **kwargs,
    162 )
    164 if data.empty:
--> 165     raise EmptyDataError()
    167 return data

OpenBBError: 
[Error] -> No results found. Try adjusting the query parameters.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser : Chrome
 - Version: Current as of 08/2024

**
I got the hard copy of the book the day it released, i.e. four days ago.

**Comment by octaviodelsueldo** [comment]
I had the same problem and it looks like yahoo finance have some problem when you extract data. I change the provider to cboe and everything run well

**Comment by jasonstrimpel** [comment]
@sandpalmtree see @octaviodelsueldo's comments above. Occasionally, Yahoo Finance flakes out. Update to the following

```
spy_equity = obb.equity.price.historical(
ticker, start_date="2021-01-01", provider="cboe"
)
```
