### ISSUE TITLE
Deprecated CHRIS Database on Nasdaq Data Link (Chapter 1 Example No Longer Works)

### ISSUE THREAD

**Issue by ZeeThirawat** [PacktPublishing/Algorithmic-Trading-with-Python-Cookbook#5]
In **Chapter 1** of the course, the example for retrieving data from Nasdaq Data Link no longer works. Specifically, in the notebook:
[01a_diving_into_continuous_futures_data_with_nasdaq_data_link.ipynb](https://github.com/PacktPublishing/Python-for-Algorithmic-Trading-Cookbook/blob/main/01.%20Acquiring%20Free%20Financial%20Market%20Data%20with%20Cutting-Edge%20Python%20Libraries/01a_diving_into_continuous_futures_data_with_nasdaq_data_link.ipynb)

The following code:

```python
nasdaqdatalink.get('CHRIS/CME_ES1')
```

fails due to the deprecation of the CHRIS database.

I contacted Nasdaq Data Link for clarification, and they informed me that:

> Unfortunately, the CHRIS database has been deprecated and is no longer updated on Nasdaq Data Link. At this time, we do not currently have an alternate data feed.

They further explained that:

> Free data feeds may be deprecated for various reasons, such as no longer meeting quality standards or due to technical issues preventing data access, etc.

This issue affects the current functionality of the example in the course and needs a replacement or update to reflect available data sources.

**Comment by datalifenyc** [comment]
I noticed the same issue. I was going to send an email to Nasdaq support (`connect@data.nasdaq.com`) too, but decided to check here first. Thanks for the info you provided.

A few additional things I noticed regarding the [Nasdaq Data Link Python API Client](https://github.com/Nasdaq/data-link-python):

1. It was last updated 2 years ago (2022-08-29). There is a possibility that it is no longer being maintained.

---

2. The example provided in the GitHub repo for [data-link-python](https://github.com/Nasdaq/data-link-python) returns the same error message:
```python
import nasdaqdatalink
data = nasdaqdatalink.get('NSE/OIL')
```
Output:
```text
JSONDecodeError
...
DataLinkError: (Status 410) Something went wrong. Please try again. If you continue to have problems, please contact us at connect@data.nasdaq.com.
```

---

3. Status code 410 is not listed on the Nasdaq Data Link documentation guide page: [ERROR CODES - API FOR TABLES DATA](https://docs.data.nasdaq.com/docs/error-codes)

According to [Mozilla's mdn web docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/410), this code is `410 Gone`: 

> The HTTP 410 Gone [client error response](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses) status code indicates that the target resource is no longer available at the origin server and that this condition is likely to be permanent. A 410 response is cacheable by default.

---

4. Digging deeper into the documentation \[[FOR_DEVELOPERS.md](https://github.com/Nasdaq/data-link-python/blob/main/FOR_DEVELOPERS.md)\], there is an alternate method for accessing the datasets:
```python
data = nasdaqdatalink.Dataset('WIKI/AAPL').data()
```

Unfortunately, the output will return the same `DataLinkError: (Status 410)` error message.

---

5. In an attempt to see if any datasets could be retrieved, I searched the Nasdaq Data Link database for [futures with "Free" filter](https://data.nasdaq.com/search?query=futures&filters=%5B%22Free%22%5D) and 2 results were returned:

![image](https://github.com/user-attachments/assets/0e940192-46cf-49b9-839b-ed6d216acf36)

- [Commodity Futures Trading Commission Reports](https://data.nasdaq.com/databases/CFTC)

![image](https://github.com/user-attachments/assets/2d64feba-825d-4516-83a7-f6da8d93d968)

![image](https://github.com/user-attachments/assets/06c487ad-7f6b-4b65-88e8-05c5d963a600)

The example provided worked for this `QDL/FON` dataset:

![image](https://github.com/user-attachments/assets/b7292821-632f-49c6-8fc8-c6682149588f)

However, the `CHRIS/CME_ES1` dataset is not available:

![image](https://github.com/user-attachments/assets/26009b91-ea7e-4a9d-813a-1c307a6a598c)

For `NSE/OIL` the response message is: `The following datatable 'NSE/OIL' does not exist.`

![image](https://github.com/user-attachments/assets/17d3f60e-127d-4cf3-b7fa-0c99514606ad)

- [IMF Cross Country Macroeconomic Statistics](https://data.nasdaq.com/data/ODA)

Page No Longer Exists

![image](https://github.com/user-attachments/assets/ebdb1acb-cd40-45df-b1ac-27928073d95a)

---

Next Steps:

I'll see if there is another way to get the equivalent dataset using an alternative API:

| Source | API |
| ------- | ---- |
|  [E-Mini S&P 500 Future Continuous Contract](https://www.marketwatch.com/investing/future/es00) | [marketwatch](https://pypi.org/project/marketwatch/) |
| [E-Mini S&P 500 Dec 24 (ES=F)](https://finance.yahoo.com/quote/ES%3DF/) | [yfinance](https://pypi.org/project/yfinance/) |

**Comment by ZeeThirawat** [comment]
> I noticed the same issue. ...

Thank you for your hard work and for sharing this valuable information.

I tried digging deeper as well, but only did your points 1-3.

Hopefully, the author will update his book.

**Comment by jasonstrimpel** [comment]
As indicated, Nasdaq deprecated the `CHRIS` dataset.
