### ISSUE TITLE
 CHRIS database deprecated

### ISSUE THREAD

**Issue by Josuerinho** [PacktPublishing/Algorithmic-Trading-with-Python-Cookbook#6]
Hi all!

It seems the CHRIS database has been deprecated. This is just FYI, in case you try to use `nasdaqdatalink.get("CHRIS/CME_ES1")` and throws anm`Status 410 Error` (see attached). I've got in contact with Nasdaq Data and they informed me of that.

Best,

Josu
![Screenshot 2024-09-29 at 3 51 57 PM](https://github.com/user-attachments/assets/04e380cd-030b-4475-bb7f-6ee8c3c42ca7)
<img width="1093" alt="Screenshot 2024-09-30 at 11 50 23 AM" src="https://github.com/user-attachments/assets/5860314c-4e93-428d-8c26-f97efaeac58c">

**Comment by jasonstrimpel** [comment]
Yes this is true. I've updated the Notebook with a notice. Thanks for letting me know.
