### ISSUE TITLE
01d_fetching_historic_futures_data_with_the_openbb_platform

### ISSUE THREAD

**Issue by dingding-ust** [PacktPublishing/Algorithmic-Trading-with-Python-Cookbook#8]
**Describe the bug**
data = obb.derivatives.futures.historical(
    "CL", start_date="2020-01-01", end_date="2022-12-31"
)

**Expected behavior**
Get data.

**Response I keep getting**
OpenBBError                               Traceback (most recent call last)
Cell In[24], line 1
----> 1 data = obb.derivatives.futures.historical(
      2     symbol="CL",
      3     expiration="2024-12",
      4     start_date="2020-01-01",
      5     end_date="2022-12-31"
      6 )

File d:\\Anaconda3\\envs\\my-quant-stack\\lib\\site-packages\\openbb_core\\app\\static\\utils\\decorators.py:90, in exception_handler.<locals>.wrapper(*f_args, **f_kwargs)
     88 if isinstance(e, OpenBBError):
     89     raise OpenBBError(f"\
[Error] -> {str(e)}").with_traceback(tb) from None
---> 90 raise OpenBBError(\
[Error] -> Unexpected error.").with_traceback(
     91     tb
     92 ) from None

File d:\\Anaconda3\\envs\\my-quant-stack\\lib\\site-packages\\pandas\\core\\indexes\\base.py:3812, in Index.get_loc(self, key)
   3807     if isinstance(casted_key, slice) or (
   3808         isinstance(casted_key, abc.Iterable)
   3809         and any(isinstance(x, slice) for x in casted_key)
   3810     ):
   3811         raise InvalidIndexError(key)
-> 3812     raise KeyError(key) from err
   3813 except TypeError:
   3814     # If we have a listlike key, _check_indexing_error will raise
   3815     #  InvalidIndexError. Otherwise we fall through and re-raise
   3816     #  the TypeError.
   3817     self._check_indexing_error(key)

OpenBBError: 
[Error] -> Unexpected error.

**Environment**
 - OS: Window 11
 - Python Version: 3. 10
 - OpenBB Version: 4. 4. 3

**Comment by jasonstrimpel** [comment]
OpenBB is a third party packaged managed by the OpenBB team. Please create an issue for them here: https://github.com/OpenBB-finance/OpenBB
